### ISSUE TITLE
Where is the Scaramuzza's affine transformation for fisheye lenses?

### ISSUE THREAD

**Issue by kaarta-BBoyle** [siposcsaba89/ocam-calib-cpp#1]
First, thank you so much for translating Scaramuzza's work to c++, this has been a godsend for me.

Scaramuzza describes an Affine transformation 2x2 matrix [c, d, e, 1] which accounts for misalignment between the camera and mirror. I'm not seeing it in the ocam_calibration output, or if it's there I'm unable to identify which numbers correspond to it. These parameters (c, d, e) are provided in Scaramuzza's matlab toolbox's calibration results.

See section 19.3 here: https://sites.google.com/site/scarabotix/ocamcalib-omnidirectional-camera-calibration-toolbox-for-matlab?authuser=0

**Comment by siposcsaba89** [comment]
Hi @kaarta-BBoyle !

Sorry for my late reply, those parameters are currently not optimized, the matrix is assumed to be identity [c, d; e 1] = [1, 0; 0, 1]. My observation was, that in my case, it was always close to identity( fisheye cameras, approx. 190 degree), so I left it out from the optimization.

BR, 
Csaba

**Comment by ZYYYY123324** [comment]
Thank you for your contribution！Is adasworks a custom library？

**Comment by siposcsaba89** [comment]
@ZYYYY123324 

Yes, that is a proprietary linear algebra library. You can use Eigen instead or your own. I will remove that example in the future.

**Comment by ZYYYY123324** [comment]
Is there any connection between these CPP files?I downloaded Eigen but couldn't find the Adasworks library.Could you help me?Looking forward to your reply.

**Comment by kaarta-BBoyle** [comment]
Thanks for the reply, the affine matrix is typically very close to identity for me as well so I suppose it's not the biggest deal.

**Comment by ZYYYY123324** [comment]
I'm sorry to bother you.But I failed to run the calibration code alone，Do I need another header file here？

**Comment by siposcsaba89** [comment]
@ZYYYY123324 
Sorry, you should be able to run the calibration application ocam-fisheye-calib as is, in the readme you can find some command line example, how to run it.

**Comment by ZYYYY123324** [comment]
OK,I'll try again.Thank you !

**Comment by ZYYYY123324** [comment]
Excuse me again, the following error occurred in the code operation：
错误	LNK2019	无法解析的外部符号 "double __cdecl calib_converter::convertOcam2Mei(class std::vector<double,class std::allocator<double> > const &,class std::vector<double,class std::allocator<double> > const &,class Eigen::Matrix<double,2,1,0,2,1> const &,class Eigen::Matrix<double,2,1,0,2,1> const &,class Eigen::Matrix<float,3,3,0,3,3> &,class std::array<float,5> &,float &)" (?convertOcam2Mei@calib_converter@@YANAEBV?$vector@NV?$allocator@N@std@@@std@@0AEBV?$Matrix@N$01$00$0A@$01$00@Eigen@@1AEAV?$Matrix@M$02$02$0A@$02$02@5@AEAV?$array@M$04@3@AEAM@Z)，函数 "bool __cdecl runCalibration(class std::vector<class std::vector<class cv::Point_<float>,class std::allocator<class cv::Point_<float> > >,class std::allocator<class std::vector<class cv::Point_<float>,class std::allocator<class cv::Point_<float> > > > >,class cv::Size_<int>,class cv::Size_<int>,enum Pattern,float,float,int,class cv::Mat &,class cv::Mat &,class std::vector<class cv::Mat,class std::allocator<class cv::Mat> > &,class std::vector<class cv::Mat,class std::allocator<class cv::Mat> > &,class std::vector<float,class std::allocator<float> > &,double &)" (?runCalibration@@YA_NV?$vector@V?$vector@V?$Point_@M@cv@@V?$allocator@V?$Point_@M@cv@@@std@@@std@@V?$allocator@V?$vector@V?$Point_@M@cv@@V?$allocator@V?$Point_@M@cv@@@std@@@std@@@2@@std@@V?$Size_@H@cv@@1W4Pattern@@MMHAEAVMat@4@3AEAV?$vector@VMat@cv@@V?$allocator@VMat@cv@@@std@@@2@4AEAV?$vector@MV?$allocator@M@std@@@2@AEAN@Z) 中引用了该符号	ocam	D:\fisheye_cali\fisheye-calib.obj	1

**Comment by siposcsaba89** [comment]
@ZYYYY123324 

Could you please open another issue? This one is for an other topic, and already closed.
