### ISSUE TITLE
CMakeLists.txt find_package(ceres) does not work

### ISSUE THREAD

**Issue by manasmacherla** [siposcsaba89/ocam-calib-cpp#4]
I think the ceres package header files have changed, when I installed the package, the files were stored in "Ceres" instead of "ceres", so I had to update my CMakeLists.txt to find_package(Ceres REQUIRED) instead of find_package(ceres REQUIRED). Please check if you are able to replicate this issue. Thanks..

**Comment by siposcsaba89** [comment]
Hi @manasmacherla 

Yes you are right, it should be find_package(Ceres REQUIRED), I will fix it.
Thanks!

**Comment by siposcsaba89** [comment]
I fixed it: 056cd13b592cea293de77455bb0ba710c97bb3f6
